version: '3'

services:
  build_cpu_demo:
    build:
      context: ./
      args:
        - JAR_PATH=target/CpuLockDownDemo.jar
    image: mcfongtw/ubuntu_java_cpu_demo:0.1
  demo:
    image: mcfongtw/ubuntu_java_cpu_demo:0.1
    privileged: true
    volumes:
      # To retrieve symbols correctly from host side
      # https://stackoverflow.com/questions/38927895/how-do-you-get-debugging-symbols-working-in-linux-perf-tool-inside-docker-contai
      - /var/lib/docker:/var/lib/docker
      # Map the /output in container to /tmp on Host
      - /tmp:/output
